import { useCallback, useEffect, useState, type ReactNode } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ExternalLink, FileText, Loader2, MessageSquareQuote, FileCode2, ClipboardList, RefreshCw } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { remeasureStatus } from '@/lib/deliveryCockpit';
import { REPORT_PUBLIC_ORIGIN } from '@/lib/findableOffer';

const call = async (body: Record<string, unknown>) => { const { data, error } = await supabase.functions.invoke('paid-client-hub', { body }); if (error || !data?.ok) throw new Error(error?.message || data?.error || 'Request failed'); return data; };
const baseline = async (action: string, lead_id: string) => { const { data, error } = await supabase.functions.invoke('paid-baseline', { body: { action, lead_id } }); if (error || !data?.ok) throw new Error(error?.message || data?.error || 'Baseline request failed'); return data; };
type Hub = { lead: Record<string, any>; onboarding: Record<string, any> | null; audit: Record<string, any> | null; runs: Record<string, any>[]; pages: Record<string, any>[] };
const Stage = ({ title, children }: { title: string; children: ReactNode }) => <Card><CardHeader className="pb-2"><CardTitle className="text-base">{title}</CardTitle></CardHeader><CardContent className="space-y-2 text-sm">{children}</CardContent></Card>;

export default function ClientHub() {
  const { leadId = '' } = useParams(); const [hub, setHub] = useState<Hub | null>(null); const [loading,setLoading] = useState(true); const [busy,setBusy] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { setHub((await call({ action: 'get', lead_id: leadId })).client); } finally { setLoading(false); } }, [leadId]); useEffect(() => { void load(); }, [load]);
  if (loading) return <div className="flex justify-center py-16"><Loader2 className="animate-spin"/></div>; if (!hub) return <div className="p-8">Client not found.</div>;
  const { lead, onboarding, audit, runs, pages } = hub; const rm = remeasureStatus(lead.remeasure_due_date, Date.now()); const bs = onboarding?.baseline_status || (audit ? 'running' : 'needs_questions');
  const runBaseline = async (action: string) => { setBusy(true); try { await baseline(action, lead.id); await load(); } finally { setBusy(false); } };
  const reportUrl = audit ? `${REPORT_PUBLIC_ORIGIN}/report/${audit.id}` : '';
  return <div className="mx-auto max-w-7xl space-y-4 py-6"><Link to="/paid-clients" className="text-xs text-muted-foreground">← Paid clients</Link><Card><CardContent className="p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold">{lead.business_name}</h1><p className="text-sm text-muted-foreground">{onboarding?.confirmed_location || lead.derived_town || lead.search_location} · {lead.website || 'No website recorded'}</p><p className="mt-2 text-sm">{lead.contact_name || 'No contact name'} · {lead.email || onboarding?.contact_email || 'No email'} · {lead.phone || 'No phone'}</p></div><div className="text-right text-sm"><div>Paid {lead.payment_date || 'date not recorded'}</div><div>{onboarding?.website_route?.replaceAll('_',' ') || 'Website route not set'}</div><div className="font-medium">Remeasure: {lead.remeasure_due_date || 'after baseline'} · {rm.label}</div></div></div><div className="mt-4 flex flex-wrap gap-2">{lead.website && <Button asChild variant="outline" size="sm"><a href={lead.website} target="_blank" rel="noreferrer"><ExternalLink className="mr-1 h-4 w-4"/>Open website</a></Button>}<Button asChild variant="outline" size="sm"><Link to="/outreach">Client details</Link></Button>{audit && <Dialog><DialogTrigger asChild><Button size="sm"><FileText className="mr-1 h-4 w-4"/>View Baseline Report</Button></DialogTrigger><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle>Baseline report</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">Client URL contains the client-safe report only. Internal report remains operator-only.</p><div className="flex gap-2"><Button asChild size="sm"><a href={reportUrl} target="_blank" rel="noreferrer">Client view</a></Button><Button asChild size="sm" variant="outline"><Link to={`/baseline/${audit.id}`}>Internal view / download</Link></Button><Button size="sm" variant="outline" onClick={() => navigator.clipboard.writeText(reportUrl)}>Copy client URL</Button></div></DialogContent></Dialog>}</div></CardContent></Card>
  <div className="grid gap-4 lg:grid-cols-2"><Stage title="1. Baseline">{bs === 'needs_questions' && <Button disabled={busy} onClick={() => void runBaseline('generate')}><RefreshCw className="mr-1 h-4 w-4"/>Prepare Baseline</Button>}{bs === 'needs_approval' && <><p>{onboarding?.baseline_questions?.length || 0} suggested questions are ready to edit and approve.</p><Button asChild><Link to={`/baseline-setup/${lead.id}`}>Edit & approve questions</Link></Button></>}{bs === 'approved' && <Button disabled={busy} onClick={() => void runBaseline('run')}>Approve & Run Baseline</Button>}{['running','complete'].includes(bs) && <><p>Status: {bs}. Persisted queue progress: {runs.map((r) => `Run ${r.run_number}: ${r.status}`).join(' · ') || 'queueing'}</p>{audit && <Button asChild variant="outline"><Link to={`/baseline/${audit.id}`}>Open internal baseline</Link></Button>}</>}</Stage>
  <Stage title="2. Welcome Pack"><p>{lead.email || lead.phone ? 'Contact details saved. Sending is not automated from this hub.' : 'Add contact details before sending.'}</p><Button variant="outline" disabled>Preview / send integration</Button></Stage>
  <Stage title="3. Action Plan">{audit?.baseline_completed_at ? <><p>Derived from the completed baseline; no second audit is run.</p><Button asChild variant="outline"><Link to={`/playbook/${audit.id}`}>Open action plan</Link></Button></> : <p>Available when the baseline completes.</p>}</Stage>
  <Stage title="4. Directories"><p>Directory opportunities are intentionally unverified until checked. Start with free/public entries; record only confirmed listings.</p><Button variant="outline" disabled>Directory catalogue integration</Button></Stage>
  <Stage title="5. Pages / Website">{pages.length ? pages.map((p) => <div key={p.id} className="rounded border p-2">{p.service || 'Page'} · {p.town || ''} — {p.status} <span className="text-muted-foreground">{p.primary_question}</span></div>) : <p>No planned pages yet.</p>}<Button asChild variant="outline"><Link to="/page-generator"><FileCode2 className="mr-1 h-4 w-4"/>Open page generator</Link></Button><p className="text-xs text-muted-foreground">Generation remains draft-only and requires operator approval before publishing.</p></Stage>
  <Stage title="6. Review Replies"><p>Use the existing review reply setup, then mark the delivery checklist when complete.</p><Button asChild variant="outline"><Link to="/review-replies"><MessageSquareQuote className="mr-1 h-4 w-4"/>Open Review Reply Setup</Link></Button></Stage>
  <Stage title="7. Remeasure"><p>Due: {lead.remeasure_due_date || 'scheduled after baseline'} · {rm.label}</p><p className="text-xs text-muted-foreground">The server replays the frozen baseline queue questions exactly; it never regenerates a remeasure set.</p>{lead.remeasure_audit_id ? <Button asChild variant="outline"><Link to={`/compare/${lead.remeasure_audit_id}`}>View Comparison</Link></Button> : <Button variant="outline" disabled>Runs automatically when due</Button>}</Stage>
  <Stage title="8. Results">{lead.remeasure_audit_id ? <Button asChild><Link to={`/compare/${lead.remeasure_audit_id}`}>View final comparison</Link></Button> : <p>Available after remeasure.</p>}</Stage></div>
  <Stage title="Fulfilment checklist"><p>Persistent delivery checklist is shared with the existing Delivery Cockpit in Outreach. Open client details to check items off and retain the same completion state.</p><Button asChild variant="outline"><Link to="/outreach"><ClipboardList className="mr-1 h-4 w-4"/>Open checklist</Link></Button></Stage></div>;
}
