import { useCallback, useEffect, useMemo, useState, type ReactNode } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Clipboard, ExternalLink, FileCode2, FileText, Loader2, Lock, MessageSquareQuote, RefreshCw, Save } from 'lucide-react';
import { invokePaidBaseline, type PaidBaseline } from '@/lib/paidBaseline';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { AuditQuestionEditor, cleanAuditQuestions } from '@/components/AuditQuestionEditor';
import { useToast } from '@/hooks/use-toast';
import { remeasureStatus } from '@/lib/deliveryCockpit';
import { REPORT_PUBLIC_ORIGIN } from '@/lib/findableOffer';
import { formatBaselineProgress } from '@/lib/baselineProgress';

type AnyRecord = Record<string, any>;
type Baseline = PaidBaseline;
type Hub = { lead: AnyRecord; onboarding: AnyRecord | null; audit: AnyRecord | null; runs: AnyRecord[]; pages: AnyRecord[] };
const call = async (body: Record<string, unknown>) => { const { data, error } = await supabase.functions.invoke('paid-client-hub', { body }); if (error || !data?.ok) throw new Error(error?.message || data?.error || 'Request failed'); return data; };
const baselineCall = invokePaidBaseline;
const Stage = ({ title, children }: { title: string; children: ReactNode }) => <Card><CardHeader className="pb-2"><CardTitle className="text-base">{title}</CardTitle></CardHeader><CardContent className="space-y-2 text-sm">{children}</CardContent></Card>;
const values = (v: unknown) => Array.isArray(v) ? v.filter(Boolean).join(', ') : String(v || '—');
const copy = async (value: string) => { if (value) await navigator.clipboard.writeText(value); };

function ClientDetailsDialog({ lead, onboarding }: { lead: AnyRecord; onboarding: AnyRecord | null }) {
  const f = (label: string, value: unknown) => <div><dt className="text-xs text-muted-foreground">{label}</dt><dd className="break-words">{String(value || '—')}</dd></div>;
  const notes = [lead.notes, lead.delivery_notes, lead.project_overview, onboarding?.standout, onboarding?.accreditations].filter(Boolean);
  return <Dialog><DialogTrigger asChild><Button variant="outline" size="sm">Client details</Button></DialogTrigger><DialogContent className="max-h-[90vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>Client details</DialogTitle></DialogHeader><div className="grid gap-4 text-sm sm:grid-cols-2">
    {f('Business name', lead.business_name)}{f('Connected lead ID', lead.id)}
    {f('Contact name', lead.contact_name)}<div><dt className="text-xs text-muted-foreground">Email</dt><dd className="flex items-center gap-2 break-all">{lead.email || onboarding?.contact_email || '—'}{(lead.email || onboarding?.contact_email) && <Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => void copy(lead.email || onboarding?.contact_email)}><Clipboard className="h-3.5 w-3.5"/></Button>}</dd></div>
    <div><dt className="text-xs text-muted-foreground">Phone / WhatsApp</dt><dd className="flex items-center gap-2">{lead.phone || '—'}{lead.phone && <Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => void copy(lead.phone)}><Clipboard className="h-3.5 w-3.5"/></Button>}</dd></div>
    <div><dt className="text-xs text-muted-foreground">Website</dt><dd>{lead.website ? <a className="text-primary underline" href={lead.website} target="_blank" rel="noreferrer">{lead.website}</a> : '—'}</dd></div>
    {f('Primary location', onboarding?.confirmed_location || lead.derived_town || lead.search_location || lead.address)}{f('Business specialism / category', lead.category || lead.search_keyword)}
    {f('Services', values(onboarding?.services_list) !== '—' ? values(onboarding?.services_list) : onboarding?.services || values(lead.services_included))}{f('Service areas', values(onboarding?.areas_list) !== '—' ? values(onboarding?.areas_list) : onboarding?.areas_wanted)}
    {f('Onboarding source', onboarding?.client_source || 'onboarding')}{f('Payment', lead.amount_paid ? `Paid ${lead.amount_paid}${lead.payment_date ? ` · ${lead.payment_date}` : ''}` : '—')}
    {f('Website route', onboarding?.website_route?.replaceAll('_', ' '))}{f('Domain', onboarding?.domain_status)}
    {f('Website manager / access', onboarding?.access_status)}{f('Baseline status', onboarding?.baseline_status)}
    {f('Baseline audit ID', lead.baseline_audit_id || onboarding?.audit_id)}{f('Remeasure date', lead.remeasure_due_date)}
    {f('GBP consent / manager', [onboarding?.gbp_consent, onboarding?.gbp_manager_email].filter(Boolean).join(' · '))}{f('Project status', lead.project_status || lead.status)}
  </div>{notes.length > 0 && <div><p className="mb-1 text-xs text-muted-foreground">Saved notes / onboarding details</p><div className="space-y-2 rounded-md border p-3 text-sm">{notes.map((note, i) => <p key={i} className="whitespace-pre-wrap">{note}</p>)}</div></div>}<p className="text-xs text-muted-foreground">Read-only here. Existing lead and onboarding records remain the source of truth.</p></DialogContent></Dialog>;
}

function BaselineSetupDialog({ leadId, open, onOpenChange, onChanged }: { leadId: string; open: boolean; onOpenChange: (open: boolean) => void; onChanged: () => Promise<void> }) {
  const { toast } = useToast(); const [data, setData] = useState<Baseline | null>(null); const [questions, setQuestions] = useState<string[]>([]); const [busy, setBusy] = useState<string | null>(null);
  const load = useCallback(async () => { if (!open) return; setBusy('load'); try { const next = await baselineCall('get', leadId); setData(next); setQuestions(next.questions); } catch (e) { toast({ title: 'Could not load baseline setup', description: e instanceof Error ? e.message : 'Try again', variant: 'destructive' }); } finally { setBusy(null); } }, [leadId, open, toast]);
  useEffect(() => { void load(); }, [load]);
  const locked = !!data && ['approved', 'running', 'complete'].includes(data.status);
  const clean = cleanAuditQuestions;
  const act = async (action: string, extra: Record<string, unknown> = {}) => { setBusy(action); try { const next = await baselineCall(action, leadId, extra); setData(next); setQuestions(next.questions); await onChanged(); return next; } catch (e) { toast({ title: 'Could not update baseline', description: e instanceof Error ? e.message : 'Try again', variant: 'destructive' }); return null; } finally { setBusy(null); } };
  const approveAndRun = async () => { const qs = clean(questions); if (!(await act('save', { questions: qs }))) return; if (!(await act('approve', { questions: qs }))) return; const started = await act('run'); if (started?.status === 'running') { toast({ title: 'Baseline queued', description: 'It continues on the server if you close this dialog.' }); onOpenChange(false); } else if (started) { toast({ title: 'Baseline approved but waiting', description: started.start_note || 'Complete the required client context, then retry.' }); } };
  const saveContext = () => data && act('save_context', { location: data.location, services: data.services, services_list: data.services_list, areas_list: data.areas_list, business_type: data.business_type, website: data.website });
  const generate = async (force = false) => {
    if (!data) return;
    await act('generate', {
      ...(force ? { force: true } : {}),
      location: data.location,
      services: data.services,
      services_list: data.services_list,
      areas_list: data.areas_list,
      business_type: data.business_type,
      website: data.website,
    });
  };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[92vh] max-w-4xl overflow-y-auto"><DialogHeader><DialogTitle>Prepare baseline</DialogTitle></DialogHeader>{!data || busy === 'load' ? <div className="flex justify-center py-12"><Loader2 className="animate-spin"/></div> : <div className="space-y-5">
    <p className="text-sm text-muted-foreground">Review context and questions before approval. Only the approved wording and order is queued and later replayed for remeasure.</p>
    <section className="rounded-md border p-3"><h3 className="mb-3 font-medium">A. Client / business context</h3><div className="grid gap-3 sm:grid-cols-2"><div><Label>Business</Label><Input value={data.business_name} disabled/></div><div><Label>Specialism / category</Label><Input value={data.business_type} disabled={locked} onChange={(e) => setData({ ...data, business_type: e.target.value })}/></div><div><Label>Website</Label><Input value={data.website} disabled={locked} onChange={(e) => setData({ ...data, website: e.target.value })}/></div><div><Label>Primary location</Label><Input value={data.location} disabled={locked} onChange={(e) => setData({ ...data, location: e.target.value })}/></div><div className="sm:col-span-2"><Label>Services (comma separated)</Label><Input value={data.services} disabled={locked} onChange={(e) => setData({ ...data, services: e.target.value })}/><p className="mt-1 text-xs text-muted-foreground">{Object.entries(data.context_sources?.service_sources ?? {}).map(([name, sources]) => `${name} (${sources.join(', ')})`).join(' · ') || 'No service facts found yet'}</p></div><div className="sm:col-span-2"><Label>Service areas (comma separated)</Label><Input value={data.areas_list.join(', ')} disabled={locked} onChange={(e) => setData({ ...data, areas_list: e.target.value.split(',').map((x) => x.trim()).filter(Boolean) })}/><p className="mt-1 text-xs text-muted-foreground">{Object.entries(data.context_sources?.area_sources ?? {}).map(([name, sources]) => `${name} (${sources.join(', ')})`).join(' · ') || 'No service-area facts found yet'}</p></div><div className="sm:col-span-2"><Label>Services list (comma separated)</Label><Input value={data.services_list.join(', ')} disabled={locked} onChange={(e) => setData({ ...data, services_list: e.target.value.split(',').map((x) => x.trim()).filter(Boolean) })}/></div></div>{data.crawl_context_at && <p className="mt-2 text-xs text-muted-foreground">Website context last refreshed {new Date(data.crawl_context_at).toLocaleString()}.</p>}{!locked && <Button className="mt-3" size="sm" variant="outline" disabled={!!busy} onClick={() => void saveContext()}><Save className="mr-1 h-4 w-4"/>Save client context</Button>}</section>
    <section className="rounded-md border p-3"><h3 className="font-medium">B. Audit setup</h3><p className="mt-1 text-sm text-muted-foreground">Paid baseline · {data.location || 'location required'} · three persisted runs. Preparation saves a draft only; it does not queue the audit.</p></section>
    <section className="rounded-md border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-medium">C. Question setup ({clean(questions).length})</h3><p className="text-sm text-muted-foreground">Edit, remove, add, paste, or regenerate before approval.</p></div>{locked ? <span className="flex items-center gap-1 text-xs text-emerald-600"><Lock className="h-3.5 w-3.5"/>Frozen</span> : <div className="flex gap-2"><Button size="sm" variant="outline" disabled={!!busy} onClick={() => void generate(true)}><RefreshCw className="mr-1 h-4 w-4"/>Regenerate</Button>{questions.length === 0 && <Button size="sm" disabled={!!busy} onClick={() => void generate()}><RefreshCw className="mr-1 h-4 w-4"/>Generate suggestions</Button>}</div>}</div>
      <div className="mt-3"><AuditQuestionEditor questions={questions} onChange={setQuestions} disabled={locked} busy={!!busy}/></div>
      {!locked && <Button className="mt-3" size="sm" variant="outline" disabled={!!busy || clean(questions).length === 0} onClick={() => void act('save', { questions: clean(questions) })}><Save className="mr-1 h-4 w-4"/>Save draft</Button>}</section>
    <section className="rounded-md border border-primary/30 bg-primary/5 p-3"><h3 className="font-medium">D. Approval + run</h3><p className="mt-1 text-sm text-muted-foreground">Approval freezes the exact text and order. The server queues that frozen set × 3.</p>{!locked && <Button className="mt-3" disabled={!!busy || clean(questions).length === 0} onClick={() => void approveAndRun()}>{busy && <Loader2 className="mr-1 h-4 w-4 animate-spin"/>}Approve &amp; Run Baseline</Button>}{data.status === 'approved' && <Button className="mt-3" disabled={!!busy} onClick={() => void act('run')}>Run approved baseline</Button>}{locked && <p className="mt-2 text-sm">Status: {data.status.replace('_', ' ')}</p>}</section>
  </div>}</DialogContent></Dialog>;
}

export default function ClientHub() {
  const { leadId = '' } = useParams(); const [hub, setHub] = useState<Hub | null>(null); const [loading, setLoading] = useState(true); const [baselineOpen, setBaselineOpen] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { setHub((await call({ action: 'get', lead_id: leadId })).client); } finally { setLoading(false); } }, [leadId]); useEffect(() => { void load(); }, [load]);
  const runs = hub?.runs ?? [];
  const progress = useMemo(() => formatBaselineProgress(runs, 3), [runs]);
  if (loading) return <div className="flex justify-center py-16"><Loader2 className="animate-spin"/></div>; if (!hub) return <div className="p-8">Client not found.</div>;
  const { lead, onboarding, audit, pages } = hub; const rm = remeasureStatus(lead.remeasure_due_date, Date.now()); const bs = onboarding?.baseline_status || (audit ? 'running' : 'needs_questions'); const reportUrl = audit ? `${REPORT_PUBLIC_ORIGIN}/report/${audit.id}` : '';
  return <div className="mx-auto max-w-7xl space-y-4 py-6"><Link to="/paid-clients" className="text-xs text-muted-foreground">← Paid clients</Link><Card><CardContent className="p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold">{lead.business_name}</h1><p className="text-sm text-muted-foreground">{onboarding?.confirmed_location || lead.derived_town || lead.search_location} · {lead.website || 'No website recorded'}</p><p className="mt-2 text-sm">{lead.contact_name || 'No contact name'} · {lead.email || onboarding?.contact_email || 'No email'} · {lead.phone || 'No phone'}</p></div><div className="text-right text-sm"><div>Paid {lead.payment_date || 'date not recorded'}</div><div>{onboarding?.website_route?.replaceAll('_',' ') || 'Website route not set'}</div><div className="font-medium">Remeasure: {lead.remeasure_due_date || 'after baseline'} · {rm.label}</div></div></div><div className="mt-4 flex flex-wrap gap-2">{lead.website && <Button asChild variant="outline" size="sm"><a href={lead.website} target="_blank" rel="noreferrer"><ExternalLink className="mr-1 h-4 w-4"/>Open website</a></Button>}<ClientDetailsDialog lead={lead} onboarding={onboarding}/>{audit && <Dialog><DialogTrigger asChild><Button size="sm"><FileText className="mr-1 h-4 w-4"/>View Baseline Report</Button></DialogTrigger><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle>Baseline report</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">Client URL contains the client-safe report only. Internal report remains operator-only.</p><div className="flex flex-wrap gap-2"><Button asChild size="sm"><a href={reportUrl} target="_blank" rel="noreferrer">Client view</a></Button><Button asChild size="sm" variant="outline"><Link to={`/baseline/${audit.id}`}>Internal view / download</Link></Button><Button size="sm" variant="outline" onClick={() => void copy(reportUrl)}>Copy client URL</Button></div></DialogContent></Dialog>}</div></CardContent></Card>
  <BaselineSetupDialog leadId={lead.id} open={baselineOpen} onOpenChange={setBaselineOpen} onChanged={load}/><div className="grid gap-4 lg:grid-cols-2"><Stage title="1. Baseline">{['needs_questions','needs_approval','approved','failed'].includes(bs) && <><p>{bs === 'needs_questions' ? 'Baseline not started.' : `Status: ${bs.replace('_', ' ')}.`}</p><Button onClick={() => setBaselineOpen(true)}><RefreshCw className="mr-1 h-4 w-4"/>{bs === 'needs_questions' ? 'Prepare Baseline' : 'Continue baseline setup'}</Button></>}{['running','complete'].includes(bs) && <><p className="font-medium">Baseline {bs === 'complete' ? 'complete' : 'running'}</p><p>{onboarding?.baseline_questions?.length || 'Saved'} questions × 3 runs</p><p className="text-muted-foreground">{progress || 'Persisted queue is being created…'}</p>{bs === 'running' && <Loader2 className="h-4 w-4 animate-spin text-primary"/>}{audit && <Button asChild variant="outline"><Link to={`/baseline/${audit.id}`}>Open internal baseline</Link></Button>}</>}</Stage>
  <Stage title="2. Welcome Pack"><p>{lead.email || lead.phone ? 'Contact details saved. Sending is not automated from this hub.' : 'Add contact details before sending.'}</p><Button variant="outline" disabled>Preview / send integration</Button></Stage><Stage title="3. Action Plan">{audit?.baseline_completed_at ? <><p>Derived from the completed baseline; no second audit is run.</p><Button asChild variant="outline"><Link to={`/playbook/${audit.id}`}>Open action plan</Link></Button></> : <p>Available when the baseline completes.</p>}</Stage><Stage title="4. Directories"><p>Directory opportunities are intentionally unverified until checked.</p><Button variant="outline" disabled>Directory catalogue integration</Button></Stage><Stage title="5. Pages / Website">{pages.length ? pages.map((p) => <div key={p.id} className="rounded border p-2">{p.service || 'Page'} · {p.town || ''} — {p.status}</div>) : <p>No planned pages yet.</p>}<Button asChild variant="outline"><Link to="/page-generator"><FileCode2 className="mr-1 h-4 w-4"/>Open page generator</Link></Button></Stage><Stage title="6. Review Replies"><Button asChild variant="outline"><Link to="/review-replies"><MessageSquareQuote className="mr-1 h-4 w-4"/>Open Review Reply Setup</Link></Button></Stage><Stage title="7. Remeasure"><p>Due: {lead.remeasure_due_date || 'scheduled after baseline'} · {rm.label}</p><p className="text-xs text-muted-foreground">The server replays the frozen baseline queue questions exactly; it never regenerates a remeasure set.</p>{lead.remeasure_audit_id ? <Button asChild variant="outline"><Link to={`/compare/${lead.remeasure_audit_id}`}>View Comparison</Link></Button> : <Button variant="outline" disabled>Runs automatically when due</Button>}</Stage><Stage title="8. Results">{lead.remeasure_audit_id ? <Button asChild><Link to={`/compare/${lead.remeasure_audit_id}`}>View final comparison</Link></Button> : <p>Available after remeasure.</p>}</Stage></div></div>;
}
