/* CONCEPT TOOLING — not part of the app, the build or the test run.
   Renders the REAL live quick-check report (buildReportData → renderReportHtml, unchanged) on the
   Doncaster fixture, then cuts out the live CTA + footer and the live stylesheet, and writes them to
   live-footer.js. The concept gallery mounts that fragment in a shadow root, so the concepts end on
   exactly the footer the live report prints — not a copy, not new copy.
   Run from the worktree root:  npx tsx docs/concepts/audit-report/extract-live-footer.ts */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { HOOK_ENGINES, initialHookStateV2 } from '../../../src/lib/hookScore.ts';
import { buildReportData } from '../../../src/lib/auditReport.ts';
import { renderReportHtml } from '../../../src/lib/aiAuditReportHtml.ts';

const BIZ = 'The Doncaster Roofing Company';
const Q = ['roof repair in Doncaster UK', 'best roofer in Doncaster', 'emergency roofer near Doncaster'];
/* [chatgpt, gemini] named? — 1 of 6, as in the concept fixture. */
const GRID: Array<[boolean, boolean]> = [[false, false], [true, false], [false, false]];
const cell = (named: boolean) => ({ named, self_named: named, answer_text: 'fixture', competitors: ['Apex Roofing Contractors Ltd'], citations: [] });
const qr = GRID.map(([c, g], i) => ({ id: `q${i}`, question: Q[i], status: 'done', result: { chatgpt: cell(c), gemini: cell(g) }, engines: [...HOOK_ENGINES] }));
const run = { id: 'r1', run_number: 1, status: 'complete', mention_rate: 0, created_at: '2026-10-06T10:00:00Z', results: { hook: initialHookStateV2(Q), competitor_cleaning: { complete: true, at: 'x', attempts: 1, errors: [] } } };
const d = buildReportData(qr as never, run as never, { businessName: BIZ, businessType: 'roofer', locationText: 'Doncaster', specialisms: '', isAggregatorUrl: () => false, hasWebsite: true });
/* offerUrl / requestCallUrl are set on the render-audit-report path (the one prospects open), so the
   Get started and Request a call buttons render as they do live. '#' keeps the concept inert. */
const html = renderReportHtml({ ...(d as object), generatedAtLabel: '6 October 2026', showOffer: true, offerUrl: '#', auditId: 'fixture', requestCallUrl: '#' } as never);

const start = html.indexOf('<section class="cta">');
const endTag = '</footer>';
const end = html.indexOf(endTag, start);
if (start < 0 || end < 0) throw new Error('live CTA/footer markers not found — the renderer changed');
const fragment = html.slice(start, end + endTag.length);
const css = [...html.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/g)].map((m) => m[1]).join('\n');
const out = resolve(import.meta.dirname, 'live-footer.js');
writeFileSync(out, '/* GENERATED by extract-live-footer.ts from the live renderer — do not edit by hand. */\nwindow.LIVE_FOOTER = ' + JSON.stringify({ css, html: fragment, generated: '2026-10-06' }) + ';\n');
console.log('wrote', out, 'fragment', fragment.length, 'css', css.length);
console.log(fragment.replace(/<!--[\s\S]*?-->/g, '').replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim());
