-- directory_businesses.description — an AI-written, factual 2-3 sentence profile for the directory
-- listing + business page, generated by the enrich-directory-business edge function (service role)
-- from the scraped data + (best-effort) the business's own website content. description_generated_at
-- caches when it was produced so views don't re-bill OpenAI. Both nullable; a null description falls
-- back to the data-derived sentence at render time. RUN IN THE SUPABASE SQL EDITOR (applied by hand).

ALTER TABLE public.directory_businesses ADD COLUMN description text;
ALTER TABLE public.directory_businesses ADD COLUMN description_generated_at timestamptz;
