// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { regionPinnedFetch } from '@/lib/edgeRegion';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  /* ⚡ Edge functions run next to the database, not next to the browser (2026-09-27) — see
     src/lib/edgeRegion.ts. Only /functions/v1/ URLs change. Keep this if the file is regenerated
     (scripts/edge-region.test.ts fails without it). */
  global: { fetch: regionPinnedFetch(SUPABASE_URL) },
});